Frontend/src/App.css
Frontend/src/components/navegation-menu/header/Header.css
Frontend/src/components/navegation-menu/header/dropdown/Dropdown.jsx
Frontend/src/components/navegation-menu/header/dropdown/DropdownContent.jsx
Frontend/src/components/navegation-menu/nav-bar/NavBar.jsx
Frontend/src/components/shortcuts/Shortcuts.jsx
Frontend/src/components/task/StatementsSelection.jsx
Frontend/src/components/task/TaskPage.css
Frontend/src/components/task/taskListAndDetails.jsx

**Descripción del PR** 
--
Este PR mejora la accesibilidad del Home de los usuarios con rol profesor solucionando algunos problemas menores de accesibilidad que hemos encontrado en la página usando distintas herramientas.
Mejoras implementadas:
- Se añadió `aria-label` a los botones “Preferencias de usuario” y “Filtrar por nombre”.
- Se corrigió el contraste en “ver soluciones” y “editar soluciones” de --Color-grey-400 a --Color-grey-800.
- Se corrigió el contraste en “rol del usuario” del header de --Color-grey-300 a --Color-grey-200.
- Se corrigió el tamaño de letra de “Fecha y hora de cierre” de las tareas activas de --text-desktop-tiny a --text-desktop-small. Y también el contraste de --Color-grey-500 a --Color-grey-700.
- Se añadió un encabezado `h1` y se modificaron varios …

Fixed some accessibility issues on the teacher's Home screen

---

Frontend/src/components/shortcuts/Shortcuts.jsx
Frontend/src/config.js

La url en el archivo config.js cambio de :
"localhost"  -->  "localhost:5173"
y un cambio en una coma en shortcuts.

The URL in localhost has been changed

---

Backend/app/controllers/registrations_controller.rb
Backend/app/controllers/sessions_controller.rb
Backend/app/controllers/statements_controller.rb
Backend/app/models/user.rb
Backend/config/routes.rb
Backend/db/migrate/20250122094224_add_role_to_users_and_remove_role_tables.rb
Backend/db/schema.rb
Backend/db/seeds.rb
Frontend/src/App.jsx
Frontend/src/components/navegation-menu/header/dropdown/Dropdown.jsx
Frontend/src/components/navegation-menu/header/dropdown/DropdownContent.jsx
Frontend/src/components/navegation-menu/nav-bar/NavBar.jsx
Frontend/src/components/navegation-menu/settings-modal/SettingsModal.css
Frontend/src/components/navegation-menu/settings-modal/SettingsModal.jsx
Frontend/src/components/private-route/PrivateRoute.jsx
Frontend/src/components/shortcuts/Shortcuts.jsx
Frontend/src/components/user/SignIn.jsx
Frontend/src/components/user/SignUp.jsx
Frontend/src/context/AuthContext.jsx
Frontend/src/context/nav-menu/NavStateProvider.jsx
Frontend/src/hooks/useAuthLogic.jsx
Frontend/src/pages/Home.jsx
Frontend/src/services/NavRoutes.js

He creado una migración para añadir el campo "role" a la tabla Users, y también eliminar las tablas User-Roles y Roles. También se han realizado los cambios necesarios en la aplicación para mantener el funcionamiento. Hay pequeños cambios eliminando console.logs innecesarios, y otros pequeños cambios no importantes (hay un cambio en el css de una modal que estaba haciendo conflicto con otra modal).
P.D.: Te puse tanto en Reviewes, como en Assigness porque no sé exactamente cual era el importante.

Issue#12 - Añadido el campo Role a la tabla Users, y eliminación de tablas User-roles y Roles

---

Backend/config/application.rb
Frontend/src/components/aux-section-two/AuxSectionTwo.jsx
Frontend/src/components/aux-section/AuxSection.jsx
Frontend/src/components/entries-section/EntriesSection.jsx
Frontend/src/components/entries-section/entry/Entry.jsx
Frontend/src/components/task/ExamInformation/ExamInformation.css
Frontend/src/components/task/ExamInformation/ExamInformation.jsx
Frontend/src/components/trial-balance/RealTimeTrialBalance.css
Frontend/src/components/trial-balance/RealTimeTrialBalance.jsx
Frontend/src/components/trial-balance/RealTimeTrialBalance.test.jsx
Frontend/src/pages/modes/exam-page/ExamPage.jsx
Frontend/src/pages/modes/practice-page/PracticePage.jsx
Frontend/src/pages/modes/task-page/TaskPage.jsx
Frontend/src/utils/dateTimeFormat.js

Se ha creado un nuevo componente RealTimeTrialBalance que muestra todas las cuentas contables con sus movimientos en el Debe y Haber para comprobar si la contabilidad cuadra. Cada línea del balance de comprobación corresponde a una cuenta contable.
La tabla se rellena de forma automática mientras el usuario rellena los datos que se corresponden al ejercicio. 
Se han solucionado algunos bugs que creaban bucles infinitos, también se han eliminado algunos console logs, etc.

Issue/7724 - Realizar componente Balance Contable

---

Frontend/src/components/aux-section/AuxSection.css
Frontend/src/components/aux-section/AuxSection.jsx
Frontend/src/components/entries-section/EntriesSection.jsx
Frontend/src/components/task/ExamInformation/ExamInformation.jsx
Frontend/src/components/trial-balance/LedgerBook.css
Frontend/src/components/trial-balance/LedgerBook.jsx
Frontend/src/components/trial-balance/LedgerBook.test.jsx

El diario mayor (también llamado libro mayor) es un registro donde se organiza toda la información contable por cuentas. En el libro diario se anotan todas las operaciones en orden cronológico, esas mismas operaciones se agrupan por cuenta contable.
Se puede ordenar por cuenta, y por apunte, por defecto se ordena por orden de aparición.

Issue/7723 - Realizar componente Diario Mayor

---

Backend/app/controllers/school_centers_controller.rb
Frontend/src/components/assignUsersToClass/AssignUserToClass.jsx
Frontend/src/components/class-group/ClassGroupForm.jsx
Frontend/src/components/user/add-users/AddUsers.jsx

Issue#114 - Corrección de errores encontrados

---

Frontend/src/components/assignTaskUser/AssignTaskUser.jsx
Frontend/src/components/assignUsersToClass/AssignUserToClass.jsx
Frontend/src/components/class-group/ClassGroupList.jsx

In the task form, when user open the student assignment modal to do some changes, if the user clicks on save button, the modal remains open.
The user is not receiving any feedback about his action. Also he needs to close it manually afterwards.
Also it was found a bug in the student assignment to class for admin user.
Changes in this PR:
1. The modal get closed right after user save the student assignment.
2. Fix student assignment to class when the role is admin.
3. Clean some dead code in the components related with the changes.
----
En el formulario de tareas, cuando el usuario abre la modal de asignación de estudiantes para realizar cambios, tras darle a guardar, la ventana modal permanece abierta.
El usuario no recibe ningún feedback. Además, debe cerrarla manualmente después.
Por …

Close modal when user save the student assignment to a task | Cerrar modal cuando el usuario guarda la tarea del estudiante en una tarea

---

Frontend/src/components/aux-section/AuxSection.jsx
Frontend/src/components/entries-section/EntriesSection.jsx
Frontend/src/pages/modes/task-page/TaskPage.jsx

Excel de incidencias, Línea 68 : El botón de "Guardar progreso" no está funcionando bien. A veces el último apunte no lo guarda adecuadamente. Al borrar un apunte pasa lo mismo. Se ve muy claro con la tarea "aaaaaaaaaaaaa" cuando el usuario "mayer" va a resolver el enunciado 2 de dicha tarea, de forma que al resolver el asiento 2 con los 3 apuntes, y luego al hacer click en "guardar progreso" el asiento no se añade y vuelve al asiento 1.
**_Nota:_** Cuando se pulsa el botón "Guardar Progreso" el asiento del enunciado cambia a "Asiento 1" aunque sea el "Asiento 4" pero si sales y entras el asiento es el 4, en algún punto se está actualizando a Asiento 1 y no lo estoy viendo. Pero la funcionalidad está.
Esto es cuando se pulsa "Guardar Progreso": (cambia a "Asiento 1")
Esto es cuando vuelvo …

resolving Guardar Progreso - Issue/8016

---

Backend/bin/import_accounts.rb

Accounts with '.' were not imported

Fix account importer

---

Backend/app/controllers/accounts_controller.rb
Backend/db/schema.rb
Frontend/src/components/entries-section/entry/entry-form/EntryForm.jsx
Frontend/src/components/modal/Modal.css
Frontend/src/services/AccountService.js

add a searchbar on the modal of the account list
didn't really change the css of the modal component just add  
for the search bar

add a searchbar on the moadl of the list account

---

Frontend/src/components/accounting-plan/ListAccountingPlan.jsx
Frontend/src/components/modal/AccountModal.css

Se ha añadido un scroll vertical en la modal para visualizar las Cuentas desde las acciones del PGC

#Issue/8022 - Vertical scroll viewing Accounts from PGC actions

---

Frontend/src/components/navigation-menu/header/Header.jsx

No entendemos para qué el icono de campana que aparece en la barra de menú suiperior a la izquierda de el icono de avatar del usuario.

Eliminar la campana del header - Issue/8048

---

Backend/app/controllers/accounting_plans_controller.rb

Se ha cambiando la estructura de la plantilla descargable para que coincida con la estructura actual que permite la importación de planes desde archivos excel y csv

#Issue/8060 - New downloadable template for upload PGCs

---

Frontend/src/components/entries-section/EntriesSection.jsx
Frontend/src/components/entries-section/entry/Entry.jsx
Frontend/src/components/entry/EntryForm.jsx
Frontend/src/components/task/TaskCreateForm.jsx
Frontend/src/hooks/useEntry.js
Frontend/src/utils/dateUtils.js

Incidencia #55 - Las fechas debería aparecer por defecto la fecha actual del sistema.
Hasta ahora las fechas de los asientos siempre eran "2024-10-10" por defecto. Ahora es la fecha del sistema.
Al crear una tarea, o una solución para un enunciado, la fecha del input será la fecha del sistema por defecto.

The default date field has the system date - issue/8044

---

Backend/app/controllers/school_centers_controller.rb
Backend/app/models/school_center.rb
Backend/db/migrate/20250515125450_add_code_to_school_centers.rb
Backend/db/schema.rb
Frontend/src/components/schoolCenters/add-school-center/AddSchoolCenter.jsx
Frontend/src/components/schoolCenters/list-school-center/ListSchoolCenter.jsx
Frontend/src/services/SchoolsServices.js

#Issue/8024 - New field Code in School Centers

---

Backend/app/controllers/accounts_controller.rb
Frontend/src/components/annotation/AnnotationForm.jsx
Frontend/src/components/entries-section/entry/entry-form/EntryForm.jsx
Frontend/src/components/entry/EntryForm.jsx
Frontend/src/components/modal/AccountSelectionModal.jsx
Frontend/src/components/modal/Modal.css
Frontend/src/components/modal/Modal.jsx
Frontend/src/components/statements/StatementPage.css
Frontend/src/hooks/useAccountSelector.tsx
Frontend/src/services/AccountService.js

accounts: fix modal search on EntryForm and add it to AnnotationForm

---

Frontend/src/components/class-group/ClassGroupForm.jsx
Frontend/src/components/class-group/ClassGroupList.jsx
Frontend/src/pages/class-group/ClassGroup.css
Frontend/src/pages/class-group/ClassGroup.jsx

Crear Grupo Clase - Issue/8014

---

Backend/app/controllers/statements_controller.rb
Frontend/src/components/statements/StatementCreateForm.jsx
Frontend/src/components/statements/StatementForm.jsx
Frontend/src/components/statements/StatementList.jsx

issue/8029 - The list of statements is refreshed and displayed correctly.

---

Frontend/src/components/shortcuts/Shortcuts.jsx
Frontend/src/components/shortcuts/shortcut/Shortcut.jsx
Frontend/src/components/statements/StatementForm.jsx
Frontend/src/components/statements/StatementList.jsx
Frontend/src/components/task/StatementsSelection.jsx
Frontend/src/components/task/TaskForm.jsx
Frontend/src/components/task/taskListAndDetails.jsx
Frontend/src/services/ShortcutRoutes.js

Se añadio una explicacion para saber que es una tarea y un enunciado.
Una "Tarea" es realmente un "Supuesto".
"Enunciado" que realmente significa "Operación u Operaciones Económicas".

Agregar tooltips y titulo en todas las partes donde salga enunciado y tarea - Issue/8045

---

Backend/app/models/school_center.rb
Backend/db/migrate/20241031155415_create_school_centers.rb
Frontend/src/components/schoolCenters/add-school-center/AddSchoolCenter.jsx

Se han agregado nuevas restricciones al modelo de school_center. No se permite que coincida el Nombre ni el Correo electrónico del centro (además del código, que ya existía como restricción).
Nueva gestión de errores en el componente de AddSchoolCenter

#Issue/8023 - Avoid duplicated school centers

---

Backend/app/controllers/class_groups_controller.rb
Backend/app/models/class_group.rb
Backend/db/migrate/20250520084905_add_fields_to_class_groups.rb
Backend/db/schema.rb
Frontend/src/components/class-group/ClassGroupForm.jsx
Frontend/src/components/class-group/ClassGroupList.jsx
Frontend/src/pages/class-group/ClassGroup.jsx
Frontend/src/services/ClassGroupService.js

New fields added to class_groups - Issue/8026

---

Backend/app/controllers/users_controller.rb
Backend/db/schema.rb
Frontend/src/components/navigation-menu/settings-modal/SettingsModal.css
Frontend/src/components/navigation-menu/settings-modal/SettingsModal.jsx

i finish here modifying the personal profile do that every person can change his password and all the sections are visible and responsive
before
after 
but i comment this section
cause dont know if ts necessary

Issue/fix password/photo modal
